apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: permissions
  namespace: default
spec:
  hosts: ["app.<DOMAIN>"]
  gateways: [ "gateway-app" ]
  http:
    - match:
      - uri:
          prefix: "/permissions"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: permissions


